### ISSUE TITLE
Typo in index.html throws error

### ISSUE THREAD

**Issue by authorbeard** [learn-co-curriculum/angular-using-ngmessages-lab#5]
Line 98 of index.html, the quotation marks are at the end of the line instead of at the end of the path name: 

```
<script src="js/app/controllers/FormController.js></script>"
```

It throws an error whenever you try to load the page, and the messages don't work. Probably introduced when adding the angular-messages script from the previous issue (#2).

**Comment by thebrianemory** [comment]
Submitted PR #6 that fixes the above issue.
